- .gitignore
- app/controllers/favourites_controller.rb
- app/controllers/follows_controller.rb
- app/controllers/maps_controller.rb
- app/controllers/spots_controller.rb
- app/controllers/stories_controller.rb
- app/controllers/users_controller.rb
- test/controllers/favourites_controller_test.rb
- test/controllers/follows_controller_test.rb
- test/controllers/maps_controller_test.rb
- test/controllers/spots_controller_test.rb
- test/controllers/stories_controller_test.rb
- test/controllers/users_controller_test.rb
Added favourites, follows, maps, spots, stories and users controllers.
> ARCH: Added controllers

- app/controllers/favourites_controller.rb
- app/views/favourites/index.html.erb
- app/views/favourites/show.html.erb
- app/views/spots/index.html.erb
- app/views/spots/show.html.erb
- config/routes.rb
Add and delete items from bucket list and see your favourites spots...
> Bucket list

- app/controllers/stories_controller.rb
- app/views/stories/new.html.erb
- app/views/stories/show.html.erb
- db/seeds.rb
FEAT: implemented adding story page and story show page
> Keiichi feature

- app/views/stories/new.html.erb
- config/routes.rb
Now we can see this new page, but not yet for uploading multiple photos at this moment. I'm now working on it.
> FEAT: fixed stories new page

- app/controllers/stories_controller.rb
- app/views/stories/new.html.erb
- app/views/stories/show.html.erb
Finished to implement story new and show page of the minimum required for our main user story
> FEAT: fixed uploading function of multipul photos

- app/controllers/spots_controller.rb
- app/models/spot.rb
- app/views/spots/_search_bar.html.erb
Fixed searching function, to be able to search with "name", "location" and "category" of Spot
> FEAT: searching function

- app/views/favourites/index.html.erb
> Category bucket list

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/stories_controller.rb
- app/views/spots/index.html.erb
- app/views/spots/show.html.erb
- app/views/stories/new.html.erb
- app/views/stories/show.html.erb
Added pathing through each page
> FEAT: Path through

- app/views/spots/_carousel.html.erb
- app/views/stories/new.html.erb
- app/views/stories/show.html.erb
fixed position of some buttons
> FEAT: fixed some buttons

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
> footer was added

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/stories_controller.rb
- app/models/story.rb
- app/views/stories/new.html.erb
Fixed uploading forms to just one button
> FEAT: Fixed uploading function of multiple photos

- app/assets/stylesheets/components/_rectangle.scss
- app/javascript/packs/application.js
- app/javascript/packs/map.js
- package-lock.json
> fixed bugs ajax

- app/views/spots/index.html.erb
> did page mobile friendly

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/controllers/stories_controller.rb
- app/javascript/components/init_select2.js
- app/javascript/packs/application.js
- app/models/question.rb
- app/models/spot.rb
- app/models/story.rb
- app/views/spots/show.html.erb
- app/views/stories/new.html.erb
- db/migrate/20200616052909_add_question_to_stories.rb
- db/schema.rb
- package.json
- yarn.lock
Changed story show page so that we can select a question on each spot.
> FEAT: Story Show Page

- app/assets/stylesheets/components/_button.scss
- app/views/spots/show.html.erb
Adding Floating Add Story button
> FEAT: Add button on spot show page

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/views/spots/show.html.erb
Added user avatar and path through to user show page
> FEAT:Added user avator on spot show page

- app/controllers/stories_controller.rb
- app/views/stories/new.html.erb
- config/initializers/simple_form.rb
> Stories bug

- config/environments/production.rb
> ARCH: added assets compile true

- db/seeds.rb
> seeds are added

- db/seeds.rb
> seeds are updated
